services:
  trailerfin:
    restart: unless-stopped
    container_name: trailerfin
    build: .
    hostname: trailerfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      com.centurylinklabs.watchtower.enable: false
    volumes:
      - /mnt:/mnt
      - /opt/trailerfin:/app
      - /etc/localtime:/etc/localtime:ro

networks:
  saltbox:
    external: true 